spring.application.name=docker-compose-spring-boot

server.port=8090

# Database connection properties
#spring.datasource.url=jdbc:postgresql://docker-compose-app-db:5432/usersDB
#spring.datasource.username=sk
#spring.datasource.password=sk@123
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/mcp_demo
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update