spring.application.name=docker-compose-spring-boot

server.port=8090

# Database connection properties
spring.datasource.url=jdbc:postgresql://docker-compose-app-db:5432/usersDB
spring.datasource.username=sagar
spring.datasource.password=sagar@123
spring.jpa.hibernate.ddl-auto=update
